Fix bashism
Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

diff --git a/.github/actions/ciproxy/start/action.yml b/.github/actions/ciproxy/start/action.yml
--- a/.github/actions/ciproxy/start/action.yml
+++ b/.github/actions/ciproxy/start/action.yml
@@ -115,20 +115,20 @@ runs:
       working-directory: ${{ inputs.working-directory }}
       run: |
         # Wait for ciproxy.pid that will be generated by CIProxy binary.
-        retryCount=0
-        while [[ ! -f "ciproxy.pid" ]]; do
-          ((retryCount++))
+        declare -i retryCount=0
+        while ! [[ -f ciproxy.pid ]]; do
+          retryCount=$((retryCount+1))
 
-          if [[ $retryCount -gt 30 ]]; then
-            echo "ERROR: CIProxy did not start properly." >&2
+          if [[ "$retryCount" -gt 30 ]]; then
+            echo "ERROR: CIProxy did not start properly."
             echo "**Stdout of CIProxy:**"
             echo '```text'
-            cat "stdout.log"
+            cat stdout.log
             echo '```'
             echo
             echo "**Stderr of CIProxy:**"
             echo '```text'
-            cat "stderr.log"
+            cat stderr.log
             echo '```'
             exit 1
           fi
