Refactor CIProxy (#68)
* Refactor CIProxy

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix go.mod and go.sum paths

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Remove pwsh for containers

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

* Fix for review comments

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

---------

Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

diff --git a/.github/actions/ciproxy/finalize/action.yml b/.github/actions/ciproxy/finalize/action.yml
--- a/.github/actions/ciproxy/finalize/action.yml
+++ b/.github/actions/ciproxy/finalize/action.yml
@@ -7,23 +7,42 @@ author: Kaito Udagawa <umireon@kaito.tokyo>
 description: Stop ciproxy for vcpkg binary caching and upload packages to the storage
 
 inputs:
-  path:
-    description: Path to CIProxy directory.
-    required: true
   pid:
     description: PID of the running ciproxy
     required: true
   ciproxy-master-token:
     description: CIProxy master token.
     required: true
-  short-hash-length:
-    description: "Length of the short hash to be used in the filename"
+  working-directory:
+    description: Working directory for CIProxy.
     required: false
-    default: "8"
+    default: .
 
 runs:
   using: composite
   steps:
+    - name: Validate inputs
+      shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
+      env:
+        CIPROXY_MASTER_TOKEN: ${{ inputs.ciproxy-master-token }}
+        PID: ${{ inputs.pid }}
+        WORKING_DIRECTORY: ${{ inputs.working-directory }}
+      run: |
+        if [[ -z "$CIPROXY_MASTER_TOKEN" ]]; then
+          echo "CIPROXY_MASTER_TOKEN is required." >&2
+          exit 1
+        fi
+
+        if [[ -z "$PID" ]]; then
+          echo "PID is required." >&2
+          exit 1
+        fi
+
+        if [[ ! -d "$WORKING_DIRECTORY" ]]; then
+          echo "WORKING_DIRECTORY '$WORKING_DIRECTORY' does not exist." >&2
+          exit 1
+        fi
+
     - name: Stop CIProxy (Windows)
       if: runner.os == 'Windows'
       shell: pwsh
@@ -36,10 +55,10 @@ runs:
         Remove-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\ciproxy" -Name "Environment" -Force
         Remove-Service -Name ciproxy
 
-    - name: Stop CIProxy (POSIX)
+    - name: Stop CIProxy (Posix)
       if: runner.os != 'Windows'
       shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
-      working-directory: ${{ inputs.path }}
+      working-directory: ${{ inputs.working-directory }}
       env:
         PID: ${{ inputs.pid }}
       run: |
@@ -50,23 +69,27 @@ runs:
           ps aux || true
           ps -p "$PID" -o pid,ppid,state,stat,comm || true
           if [[ "$count" -ge 10 ]]; then
-            echo "ERROR: Ciproxy did not stop after 30 seconds!"
+            echo "ERROR: CIProxy did not stop after 30 seconds!"
             exit 1
           fi
           sleep 3
           count=$((count+1))
         done
 
-        echo "Ciproxy gracefully exited."
+        echo "CIProxy gracefully exited."
 
     - name: Check if vcpkg artifacts exist
       id: check-artifacts
-      shell: bash --noprofile --norc -euo pipefail {0}
-      working-directory: ${{ inputs.path }}
+      shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
+      working-directory: ${{ inputs.working-directory }}
       run: |
-        shopt -s nullglob
+        if [[ ! -d "vcpkg_artifacts" ]]; then
+          echo "No vcpkg artifact directory found." >&2
+          exit 1
+        fi
+
         files=(vcpkg_artifacts/*)
-        if [[ -d vcpkg_artifacts ]] && [ "${#files[@]}" -gt 0 ]; then
+        if [[ ${#files[@]} -gt 0 ]]; then
           echo "Found ${#files[@]} vcpkg artifact(s)."
           for file in "${files[@]}"; do
             echo "- $file"
@@ -82,24 +105,23 @@ runs:
       if: steps.check-artifacts.outputs.EXISTS == 'true'
       uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
       with:
-        subject-path: ciproxy/vcpkg_artifacts/*
+        subject-path: ${{ inputs.working-directory }}/vcpkg_artifacts/*
 
     - name: Upload build provenance of vcpkg artifacts to CDN
       if: steps.check-artifacts.outputs.EXISTS == 'true'
       shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
-      working-directory: ${{ inputs.path }}
+      working-directory: ${{ inputs.working-directory }}
       env:
-        CIPROXY_MASTER_TOKEN: ${{ inputs.ciproxy-master-token }}
-        JOB_ID: ${{ github.job }}
         BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
-        SHORT_HASH_LENGTH: ${{ inputs.short-hash-length }}
+        CIPROXY_MASTER_TOKEN: ${{ inputs.ciproxy-master-token }}
       run: |
         jq -c . "$BUNDLE_PATH" > attestation.jsonl
 
         FULL_HASH=$(sha256sum attestation.jsonl | awk '{print $1}')
-        SHORT_HASH=${FULL_HASH:0:$SHORT_HASH_LENGTH}
+        SHORT_HASH=${FULL_HASH:0:8}
         FILENAME="${GITHUB_REPOSITORY/\//@}@$GITHUB_RUN_ID@$GITHUB_RUN_ATTEMPT@$GITHUB_JOB@$SHORT_HASH.jsonl"
-        echo "Uploading $FILENAME"
+
+        echo "Uploading $FILENAME..."
 
         ACCESS_TOKEN=$(curl -fsS -X POST -d "master_token=$CIPROXY_MASTER_TOKEN" https://readwrite.vcpkg-obs.kaito.tokyo/token)
         printf "::add-mask::%s\n" "$ACCESS_TOKEN"
@@ -115,5 +137,5 @@ runs:
     - name: Upload vcpkg artifacts to CDN
       if: steps.check-artifacts.outputs.EXISTS == 'true'
       shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
-      working-directory: ${{ inputs.path }}
+      working-directory: ${{ inputs.working-directory }}
       run: awk 'FNR==1 && NR!=1 {print "next"} {print}' vcpkg_curlscripts/* | curl -Z -fL -K -
