Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -30,12 +30,12 @@ jobs:
     steps:
       - name: Get access token
         run: |
-          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}")
+          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
           if [[ -z "$ACCESS_TOKEN" ]]; then
             echo "Failed to get access token"
             exit 1
           fi
-          printf 'VCPKG_BINARY_SOURCES="clear;http,https://vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
+          printf 'VCPKG_BINARY_SOURCES="clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
           echo "::add-mask::$ACCESS_TOKEN"
 
       - name: Checkout
@@ -62,12 +62,12 @@ jobs:
     steps:
       - name: Get access token
         run: |
-          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}")
+          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
           if [[ -z "$ACCESS_TOKEN" ]]; then
             echo "Failed to get access token"
             exit 1
           fi
-          printf 'VCPKG_BINARY_SOURCES="clear;http,https://vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
+          printf 'VCPKG_BINARY_SOURCES="clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
           echo "::add-mask::$ACCESS_TOKEN"
 
       - name: Checkout
@@ -95,12 +95,12 @@ jobs:
       - name: Get access token
         shell: bash
         run: |
-          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}")
+          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
           if [[ -z "$ACCESS_TOKEN" ]]; then
             echo "Failed to get access token"
             exit 1
           fi
-          printf 'VCPKG_BINARY_SOURCES="clear;http,https://vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
+          printf 'VCPKG_BINARY_SOURCES="clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
           echo "::add-mask::$ACCESS_TOKEN"
 
       - name: Checkout
@@ -126,6 +126,16 @@ jobs:
     timeout-minutes: 60
 
     steps:
+      - name: Get access token
+        run: |
+          ACCESS_TOKEN=$(curl -fsSL -X POST -d "master_token=${{ secrets.MASTER_TOKEN }}" https://readwrite.vcpkg-obs.kaito.tokyo/token)
+          if [[ -z "$ACCESS_TOKEN" ]]; then
+            echo "Failed to get access token"
+            exit 1
+          fi
+          printf 'VCPKG_BINARY_SOURCES="clear;http,https://readwrite.vcpkg-obs.kaito.tokyo/binarycache/{name}/{version}/{sha},Authorization: Bearer %s"\n' "$ACCESS_TOKEN" >> "$GITHUB_ENV"
+          echo "::add-mask::$ACCESS_TOKEN"
+
       - name: Checkout
         uses: actions/checkout@v5
 
