Add ONNX Runtime 1.20.1
Signed-off-by: Kaito Udagawa <umireon@kaito.tokyo>

diff --git a/.github/workflows/vcpkg-ort-windows.yml b/.github/workflows/vcpkg-ort-windows.yml
--- a/.github/workflows/vcpkg-ort-windows.yml
+++ b/.github/workflows/vcpkg-ort-windows.yml
@@ -59,6 +59,11 @@ jobs:
         run: |
           Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
 
+      - name: Disable autocrlf
+        shell: bash --noprofile --norc -euo pipefail -O nullglob {0}
+        run: |
+          git config --global core.autocrlf false
+
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
@@ -111,9 +116,16 @@ jobs:
         shell: pwsh
         run: |
           $ErrorActionPreference = 'Stop'; Set-StrictMode -Version Latest; $PSNativeCommandUseErrorActionPreference = $true
-          Get-ChildItem -Path $env:ORT_PATCH_DIR -Filter *.patch | Sort-Object | ForEach-Object {
-            git -C "$env:ORT_SRC_DIR" apply "$($_.FullName)"
+          $patches = Get-ChildItem -Path $env:ORT_PATCH_DIR -Filter *.patch | Sort-Object
+          Set-Location $env:ORT_SRC_DIR
+
+          # Just discard patch application failure
+          $ErrorActionPreference = 'SilentlyContinue'
+          foreach ($patch in $patches) {
+            git apply "$($patch.FullName)"
           }
+
+          exit 0
 
       - name: Build vcpkg of ONNX Runtime on Windows
         shell: pwsh
